### ISSUE TITLE
Cannot debug dynamic java activity

### ISSUE THREAD

**Issue by jbrojdeCTL** [CenturyLinkCloud/mdw-studio#69]
Execution will stop at debug point set within dynamic java activity code.  However, execution cannot be stepped after that, and execution hangs (will not continue execution/come out of activity).

**Comment by donaldoakes** [comment]
This was supposed to have been fixed with #45.

Still it can be reproduced with Studio 1.2.1 installed from the marketplace.  Build 1.2.2-SNAPSHOT installed locally on IntelliJ 2018.3.5 seems to fix the issue.  This has just been published to beta channel: https://plugins.jetbrains.com/plugin/11095-mdw-studio.  Will test to confirm once approved.

**Comment by donaldoakes** [comment]
Fixed in 1.2.2-SNAPSHOT installed per these instructions:
http://centurylinkcloud.github.io/mdw/docs/guides/mdw-studio/#11-installation

Confirmation on Windows is pending.
